mongo students_service_3 students_service/db_scripts/setup_db_3.js
mongo students_service_2 students_service/db_scripts/setup_db_2.js
mongo students_service_1 students_service/db_scripts/setup_db_1.js